version: 0.0
os: linux
files:
  - source: ./target/spring-boot-web-1.0.0-SNAPSHOT.jar
    destination: /home/ec2-user/SampleProductApp
hooks:
  BeforeInstall:
    - location: ./scripts/install_dependencies
      timeout: 300
      runas: root
    - location: ./scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./scripts/stop_server
      timeout: 300
      runas: root

