version: 0.2

phases:
  pre_build:
    commands:
      - sudo yum install -y java-1.8.0-openjdk-devel
      - java -version
      - echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" | sudo tee -a /etc/profile
      - . /etc/profile
	  
      - wget http://www-us.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
      - tar -zxvf apache-maven-3.5.3-bin.tar.gz
      - sudo mv ./apache-maven-3.5.3 /opt
      - sudo chown -R root:root /opt/apache-maven-3.5.3
      - sudo ln -s /opt/apache-maven-3.5.3 /opt/apache-maven
      - echo 'export PATH=$PATH:/opt/apache-maven/bin' | sudo tee -a /etc/profile
      - . /etc/profile
      - mvn --version
  build:
    commands:
      - echo Build of SampleProductApp started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-boot-web-1.0.0-SNAPSHOT.jar