version: 0.2

phases:
  pre_build:
    commands:
      - wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz"
      - tar xzf jdk-8u161-linux-x64.tar.gz
      - sudo mv ./jdk1.8.0_161 /opt
      - alternatives --install /usr/bin/java java /opt/jdk1.8.0_161/bin/java 2
      - alternatives --install /usr/bin/jar jar /opt/jdk1.8.0_161/bin/jar 2
      - alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_161/bin/javac 2
      - java -version
      - export JAVA_HOME=/opt/jdk1.8.0_161
      - export JRE_HOME=/opt/jdk1.8.0_161/jre
      - export PATH=$PATH:/opt/jdk1.8.0_161/bin:/opt/jdk1.8.0_161/jre/bin
      - . /etc/profile
      - wget http://www-us.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
      - tar -zxvf apache-maven-3.5.3-bin.tar.gz
      - sudo mv ./apache-maven-3.5.3 /opt
      - sudo chown -R root:root /opt/apache-maven-3.5.3
      - sudo ln -s /opt/apache-maven-3.5.3 /opt/apache-maven
      - echo 'export PATH=$PATH:/opt/apache-maven/bin' | sudo tee -a /etc/profile
      - . /etc/profile
      - mvn --version
  build:
    commands:
      - echo Build of SampleProductApp started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-boot-web-1.0.0-SNAPSHOT.jar
