version: 0.2

phases:
  pre_build:
    commands:
      - mvn --version
  build:
    commands:
      - echo Build of SampleProductApp started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-boot-web-1.0.0-SNAPSHOT.jar
    - appspec.yml
    - 'scripts/**/*'
